# Generated by Django 3.1.7 on 2021-03-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pat',
            name='prescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pat',
            name='symptoms',
            field=models.TextField(null=True),
        ),
    ]
