# Generated by Django 3.1.7 on 2021-05-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210322_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Slot1', models.IntegerField(default=0)),
                ('Slot2', models.IntegerField(default=0)),
                ('Slot3', models.IntegerField(default=0)),
                ('Slot4', models.IntegerField(default=0)),
                ('Slot5', models.IntegerField(default=0)),
                ('Slot6', models.IntegerField(default=0)),
                ('Slot7', models.IntegerField(default=0)),
                ('Slot8', models.IntegerField(default=0)),
                ('Slot9', models.IntegerField(default=0)),
                ('Slot10', models.IntegerField(default=0)),
                ('Slot11', models.IntegerField(default=0)),
                ('Slot12', models.IntegerField(default=0)),
                ('Slot13', models.IntegerField(default=0)),
                ('Slot14', models.IntegerField(default=0)),
                ('Slot15', models.IntegerField(default=0)),
                ('Slot16', models.IntegerField(default=0)),
                ('Slot17', models.IntegerField(default=0)),
                ('Slot18', models.IntegerField(default=0)),
                ('Slot19', models.IntegerField(default=0)),
                ('Slot20', models.IntegerField(default=0)),
            ],
        ),
    ]
