# Generated by Django 3.1.7 on 2021-05-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210530_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='Slot11',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot12',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot13',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot14',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot15',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot17',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot18',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot19',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='Slot20',
        ),
    ]
